apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: team-taurus-backend
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: team-taurus-backend-triggerbinding
      template:
        ref: team-taurus-backend-triggertemplate
