apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: team-taurus-backend-triggerbinding
spec:
  params:
    - name: namespace
      value: team-taurus-backend
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gitrepositoryname
      value: $(body.repository.name)
