apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
  - name: deploy-trigger-for-backend
    interceptors:
    - github:
        eventTypes: ["push"]
    - cel:
        filter: "body.repository.name == 'team-taurus-backend' && body.ref.split('/')[2] == 'master'"
stringData:
  token: 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
  secret: team-taurus-backend-gh-pat

