apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: team-taurus-backend-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: team-taurus-backend-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: wataru-nishiki-pvc

